app/__init__.py
import os

from flask import Flask, render_template

from app.routes.home import home
from app.routes.api import api


def create_app(test_config=None):
    """Create and configure an instance of the Flask application."""
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        # a default secret that should be overridden by instance config
        SECRET_KEY='dev'
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile("config.py", silent=True)
    else:
        # load the test config if passed in
        app.config.update(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    @app.errorhandler(404)
    def not_found_page(error):
        return render_template('404.html', error_message=error), 404

    app.register_blueprint(api)
    app.register_blueprint(home)

    return app

app/routes/api.py
from genericpath import exists
import json

from flask import Blueprint, jsonify, request, url_for
from markdown import markdown
import yaml

from app.utils.constants import (
    CODE_NOT_FOUND_MSG, CODES_DIR_PATH, DIR_NOT_FOUND_MSG,
    FILE_ERROR_READING_MSG)
from app.utils.html import strip_tags


api = Blueprint("api", __name__, url_prefix='/api')


@api.route("/<int:code>/")
def get_api_code(code: int):
    if not exists(CODES_DIR_PATH):
        return {"message": DIR_NOT_FOUND_MSG}, 404

    md_file_path = CODES_DIR_PATH.joinpath(f"{code}.md")

    if not md_file_path.is_file():
        return {"message": CODE_NOT_FOUND_MSG}, 404

    try:
        with open(md_file_path, "r", encoding="utf-8") as md_file:
            text = md_file.read()
    except IOError:
        return {"message": FILE_ERROR_READING_MSG.format("MD")}, 500

    content_divided = text.split("---")
    content_meta = yaml.safe_load(content_divided[1])
    content_body = markdown(content_divided[2])

    try:
        with CODES_DIR_PATH.joinpath("classes.json").open() as classes_from_json:
            http_codes_categories = json.load(classes_from_json)
    except IOError:
        return {"message": FILE_ERROR_READING_MSG.format("JSON")}, 500

    category_title = str(
        http_codes_categories[str(content_meta["set"])]["title"])

    location = request.host_url[:-1] + url_for("home.get_code", code=code)

    json_resp = {
        "location": location,
        "status_code": content_meta["code"],
        "category": category_title.replace("&times;&times; ", "-").split("-")[1],
        "title": content_meta["title"],
        "description": strip_tags(content_body.split("\n")[0])
    }
    return jsonify(json_resp), 200

app/routes/home.py
from os.path import exists
import json
import re

from flask import Blueprint, render_template, request, send_from_directory
from markdown import markdown
import yaml

from app.utils.constants import (
    CODE_NOT_FOUND_MSG, CODES_DIR_PATH, CONTENTS_DIR_PATH, DIR_NOT_FOUND_MSG,
    FILE_ERROR_READING_MSG, MD_HEADER_META_REGEX)
from app.utils.html import strip_tags
from app.utils.md import MD_EXTENSIONS, MD_EXTENSION_CONFIGS

home = Blueprint("home", __name__)


@home.route("/")
def index():
    if not exists(CODES_DIR_PATH):
        return render_template("404.html", error_message=DIR_NOT_FOUND_MSG), 404

    try:
        with CODES_DIR_PATH.joinpath("classes.json").open() as classes_from_json:
            http_codes_collection = json.load(classes_from_json)
    except IOError:
        return render_template("404.html", error_message=FILE_ERROR_READING_MSG.format("JSON")), 404

    try:
        with open(CONTENTS_DIR_PATH.joinpath("index.md"), "r", encoding="utf-8") as index_file:
            index_md_content = index_file.read()
            headline = markdown(index_md_content.split("---")[2],
                                extension_configs=MD_EXTENSION_CONFIGS)
    except IOError:
        return render_template("404.html", error_message=FILE_ERROR_READING_MSG.format("MD"))

    for item in CODES_DIR_PATH.glob("*.md"):
        if item.is_file():
            try:
                with open(item, "r", encoding="utf-8") as md_file:
                    md_file_content = md_file.read()

                md_content_divided = md_file_content.split("---")

                file_content_meta = yaml.safe_load(md_content_divided[1])

                code = {
                    "code": file_content_meta["code"],
                    "set": file_content_meta["set"],
                    "title": file_content_meta["title"]
                }

                if str(code["set"]) in http_codes_collection.keys():
                    if "codes" in http_codes_collection[str(code["set"])]:
                        http_codes_collection[str(
                            code["set"])]["codes"].append(code)
                        http_codes_collection[str(code["set"])]["codes"] = sorted(
                            http_codes_collection[str(
                                code["set"])]["codes"], key=lambda item: item.get("code")
                        )
                    else:
                        http_codes_collection[str(code["set"])]["codes"] = [
                            code]
            except:
                continue

    context = {
        "headline": headline,
        "http_codes_collection": http_codes_collection
    }

    return render_template("index.html", **context)


@home.route("/about/")
def about():
    return render_template("about.html")


@home.route("/contact/")
def contact():
    return render_template("contact.html")


@home.route("/humans.txt")
def humans():
    return send_from_directory(CONTENTS_DIR_PATH, request.path[1:])


@home.route("/<int:code>/")
def get_code(code: int):
    if not exists(CODES_DIR_PATH):
        return render_template("404.html", error_message=DIR_NOT_FOUND_MSG), 404

    code_md_file_path = CODES_DIR_PATH.joinpath(f"{code}.md")

    if not code_md_file_path.is_file():
        return render_template("404.html", error_message=CODE_NOT_FOUND_MSG), 404

    try:
        with open(code_md_file_path, "r", encoding="utf-8") as code_md_file:
            code_md_content = code_md_file.read()
    except IOError:
        return render_template("404.html", error_message=FILE_ERROR_READING_MSG.format("MD")), 404

    md_content_divided = code_md_content.split("---")

    content_meta = yaml.safe_load(md_content_divided[1])
    content_body = markdown(md_content_divided[2],
                            extensions=[*MD_EXTENSIONS],
                            extension_configs=MD_EXTENSION_CONFIGS)
    content_footnotes = markdown(md_content_divided[3],
                                 extensions=[*MD_EXTENSIONS],
                                 extension_configs=MD_EXTENSION_CONFIGS)

    content = markdown(re.sub(MD_HEADER_META_REGEX, '', code_md_content),
                       extensions=[*MD_EXTENSIONS],
                       extension_configs=MD_EXTENSION_CONFIGS)

    page_description = strip_tags(content_body.split("\n")[0])

    try:
        with CODES_DIR_PATH.joinpath("classes.json").open() as classes_from_json:
            http_codes_collection = json.load(classes_from_json)
    except IOError:
        return render_template("404.html", error_message=FILE_ERROR_READING_MSG.format("JSON")), 404

    context = {
        "page_description": page_description,
        "content_meta": content_meta,
        "content_body": content_body,
        "content_footnotes": content_footnotes,
        "content": content,
        "http_codes_collection": http_codes_collection
    }
    return render_template("code.html", **context)

app/templates/about.html
<h1>About</h1>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}HTTP Status Codes &mdash; httpstatuscodes.org{% endblock title %}</title>
    <meta name="description" content="{% block description %}HTTP Status Code directory, with definitions, details and helpful code references.{% endblock description %}">
    <meta name="keywords" content="{% block keywords %}http status, http status codes, status codes, http codes{% endblock keywords %}">
    <link type="text/plain" rel="author" href="{{ url_for('home.humans') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

app/templates/code.html
{% extends "base.html" %}
{% block title %}{{ content_meta.code }} {{ content_meta.title }} &mdash; {{ super() }}{% endblock title %}
{% block description %}{{ page_description }}{% endblock description %}
{% block keywords %}{{ content_meta.code }} {{ content_meta.title }}, {{ content_meta.code }}, {{ content_meta.title }}, {{ content_meta.code }} status code, {{ content_meta.code }} http status code, {{ super() }}{% endblock keywords %}
{% block content %}
<section class="content one">
<span class="subtitle">{{ http_codes_collection[content_meta["set"]|string]["title"] | safe }}</span>
<h1>{{ content_meta.code }} {{ content_meta.title }}</h1>
{{ content|safe }}
</section>
{% endblock content %}

app/templates/contact.html
<h1>Contact</h1>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<section class="content one">
{{ headline|safe }}
</section>
<ul class="share">
    <li><a href="https://twitter.com/intent/tweet?hashtags=httpstatuscodes&text=Helpful%20HTTP%20Status%20Code%20reference%20site&url=https%3A%2F%2Fhttpstatuscodes.org">&commat; Share on Twitter</a></li>
    <li><a href="https://github.com/huarcaya/httpstatuscodes.org">&bigstar; Star on GitHub</a></li>
    <li><a href="https://gitlab.com/huarcaya/httpstatuscodes.org">&bigstar; Star on GitLab</a></li>
</ul>
<section class="container codes">
    <ul>
    {% for x in http_codes_collection.values() %}
        <li class="mt-4">
            <span class="set">{{x["title"]|safe}}</span>
            <ul class="mt-1">
            {% for y in x["codes"] %}
                <li>
                    <a class="space-x-2" href="{{url_for('home.get_code', code=y['code'])}}">
                        <span class="number">{{y["code"]}}</span> <span>{{y["title"]}}</span>
                    </a>
                    <a class="text-xs" href="{{url_for('api.get_api_code', code=y['code'])}}">[json]</a>
                </li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
</section>
{% endblock content %}